CREATE TABLE IF NOT EXISTS :table (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	feed_id BIGINT UNSIGNED NOT NULL,
	ip_address VARCHAR(45) NOT NULL,
	user_agent VARCHAR(255) NOT NULL,
	accessed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY (id),
	INDEX (feed_id),
	INDEX (accessed_at)
)
